title: AI Conference Deadlines # (Maintained by @nduarte)
# email: nduarte@edu
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Nuno Duarte

domain: "nunoduarte.github.io"
baseurl: ""

markdown: kramdown
ga_id: UA-36274081-2
